import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Search,MapPin,Users,CalendarDays,Bookmark,Upload,Loader2}from'lucide-react';import'./styles.css';

type Paper={year?:number;title?:string;source?:string};type Person={name:string;org?:string;department?:string;title?:string;direction?:string;score?:number;whyNow?:string;products?:string[];office?:string;campus?:string;email?:string;phone?:string;papers?:Paper[];projects?:string[];equipment?:string[];source?:string};type EventItem={name:string;date?:string;city?:string;theme?:string;value?:number;why?:string;people?:string[];products?:string[];source?:string};type View='today'|'person'|'school'|'scope'|'events'|'import'|'saved';
const SAVED='radar.saved.v5';function readSaved():Person[]{try{return JSON.parse(localStorage.getItem(SAVED)||'[]')}catch{return[]}}function writeSaved(v:Person[]){localStorage.setItem(SAVED,JSON.stringify(v))}
let requestChain:Promise<any>=Promise.resolve();let waiting=0;async function queuedPost(body:any,onQueue:(n:number)=>void){waiting++;onQueue(waiting);const run=async()=>{waiting--;onQueue(waiting);const r=await fetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({error:'服务返回异常'}));if(!r.ok)throw new Error(j.error||'检索失败');return j};const task=requestChain.then(run,run);requestChain=task.catch(()=>{});return task}
function sortPapers(p:Paper[]=[]){return [...p].sort((a,b)=>(b.year||0)-(a.year||0))}
function App(){const[view,setView]=useState<View>('today');const[busy,setBusy]=useState(false);const[q,setQ]=useState(0);const[err,setErr]=useState('');const[result,setResult]=useState<any>(null);const[name,setName]=useState('');const[org,setOrg]=useState('');const[school,setSchool]=useState('上海体育大学');const[scope,setScope]=useState('');const[eventScope,setEventScope]=useState('');const[raw,setRaw]=useState('');const[saved,setSaved]=useState<Person[]>(readSaved());
 const run=async(body:any)=>{setBusy(true);setErr('');try{const j=await queuedPost(body,setQ);setResult(j)}catch(e:any){setErr(e.message||'检索失败')}finally{setBusy(false)}};const save=(p:Person)=>{const n=[p,...saved.filter(x=>!(x.name===p.name&&x.org===p.org))];setSaved(n);writeSaved(n)};
 const tabs:[View,string,any][]=[['today','今日机会',Search],['person','找老师',Users],['school','学校扫雷',MapPin],['scope','找潜客',Search],['events','会议雷达',CalendarDays],['import','名单挖掘',Upload],['saved','待开发',Bookmark]];
 return <div className="app"><header><h1>科研客户开拓雷达 <span>V5.1</span></h1><p>发现谁值得找 · 为什么现在找 · 去哪里碰到 · 拿什么产品切入</p><div className="topnav">{tabs.map(([k,t,I])=><button key={k} className={view===k?'active':''} onClick={()=>{setView(k);setResult(null);setErr('')}}><I size={16}/>{t}</button>)}</div></header><main>{q>0&&<div className="queue">已有 {q} 个检索任务排队，系统会自动按顺序执行，无需重复点击。</div>}{err&&<div className="error">{err}</div>}
 {view==='today'&&<Panel title="今日机会" desc="从新论文、新项目/基金、新实验室、近期会议等信号里找‘为什么现在值得联系’的老师。"><textarea value={scope} onChange={e=>setScope(e.target.value)} placeholder="可限定地区或方向，例如：华东 + 食品感官；留空则广泛发现"/><Go busy={busy} text="发现近期机会" onClick={()=>run({mode:'opportunities',scope})}/><People data={result?.candidates} save={save}/></Panel>}
 {view==='person'&&<Panel title="老师深度调研" desc="重点看近期研究、项目、已用设备、公开联系方式和办公室；不再生成微信/邮件/会前邀约/下一步话术。"><input value={name} onChange={e=>setName(e.target.value)} placeholder="老师姓名"/><input value={org} onChange={e=>setOrg(e.target.value)} placeholder="学校 / 单位（可留空）"/><Go busy={busy} text="联网调研" disabled={!name.trim()} onClick={()=>run({mode:'person',name,org})}/><People data={result?.candidates} save={save}/></Panel>}
 {view==='school'&&<Panel title="学校 / 实验室扫雷" desc="优先找值得陌拜的老师，并补公开办公室、校区、工作邮箱和办公电话。"><input value={school} onChange={e=>setSchool(e.target.value)} placeholder="学校 / 学院 / 实验室"/><Go busy={busy} text="扫描值得开发的老师" disabled={!school.trim()} onClick={()=>run({mode:'school',school})}/>{result?.route&&<div className="route"><b>陌拜路线建议</b><br/>{result.route}</div>}<People data={result?.candidates} save={save}/></Panel>}
 {view==='scope'&&<Panel title="范围找潜客" desc="按地区、学校、研究方向批量发现潜在科研客户。"><textarea value={scope} onChange={e=>setScope(e.target.value)} placeholder="例如：杭州 + 食品感官；上海 + 运动疲劳；自然疗愈 + 风景园林"/><Go busy={busy} text="发现潜客" disabled={!scope.trim()} onClick={()=>run({mode:'scope',scope})}/><People data={result?.candidates} save={save}/></Panel>}
 {view==='events'&&<Panel title="会议 / 展会雷达" desc="只找从搜索当天往后的活动，关注科研设备开拓价值、目标人群和可切入产品。"><input value={eventScope} onChange={e=>setEventScope(e.target.value)} placeholder="可填方向/地区，例如：食品感官、体育、心理、康复"/><Go busy={busy} text="发现未来会议 / 展会" onClick={()=>run({mode:'events',scope:eventScope})}/><Events data={result?.events}/></Panel>}
 {view==='import'&&<Panel title="名单挖掘 / 批量导入" desc="把同行论文集里整理出的‘姓名 + 学校’、旧客户名单或 CSV 文本粘进来，先批量识别，再按优先级深挖。"><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'每行一个：姓名 学校\n李辉 集美大学\n王老师 上海体育大学'} /><Go busy={busy} text="识别并判断开发价值" disabled={!raw.trim()} onClick={()=>run({mode:'import',text:raw})}/><People data={result?.candidates} save={save}/></Panel>}
 {view==='saved'&&<Panel title={`待开发 ${saved.length}`} desc="这里只保留轻量收藏，不做复杂 CRM。">{saved.length===0?<div className="empty">还没有收藏老师。</div>:<People data={saved} save={save}/>}</Panel>}
 </main></div>}
function Panel({title,desc,children}:{title:string;desc:string;children:any}){return <section className="card"><h2>{title}</h2><p className="muted">{desc}</p>{children}</section>}
function Go({busy,text,onClick,disabled}:{busy:boolean;text:string;onClick:()=>void;disabled?:boolean}){return <button className="primary" disabled={busy||disabled} onClick={onClick}>{busy?<><Loader2 size={17} className="spin"/>正在联网检索…</>:text}</button>}
function People({data=[],save}:{data?:Person[];save:(p:Person)=>void}){if(!data?.length)return null;return <div className="list">{data.map((p,i)=><PersonCard key={`${p.name}-${p.org}-${i}`} p={p} save={save}/>)}</div>}
function PersonCard({p,save}:{p:Person;save:(p:Person)=>void}){const papers=useMemo(()=>sortPapers(p.papers),[p.papers]);return <div className="item"><div className="itemTop"><div><b style={{fontSize:20}}>{p.name}</b>{p.title&&<span className="tag" style={{marginLeft:6}}>{p.title}</span>}<div>{[p.org,p.department,p.campus].filter(Boolean).join(' · ')}</div><div className="muted">{p.direction}</div></div><div className="score"><b>{p.score??'-'}</b>/100</div></div>{p.products?.length?<div className="tags">{p.products.map(x=><span className="tag" key={x}>{x}</span>)}</div>:null}{p.whyNow&&<div className="hint"><b>为什么值得开发</b><br/>{p.whyNow}</div>}<div className="contact">{p.office&&<div>📍 {p.office}</div>}{p.email&&<div>✉️ {p.email}</div>}{p.phone&&<div>☎️ {p.phone}</div>}{p.source&&<div>来源：{p.source}</div>}</div>{p.equipment?.length?<div className="section"><h3>已确认使用过的设备 / 方法</h3><div className="muted">{p.equipment.join('、')}</div></div>:null}{p.projects?.length?<div className="section"><h3>近期项目 / 基金线索</h3>{p.projects.map((x,i)=><div className="muted" key={i}>• {x}</div>)}</div>:null}{papers.length?<div className="section"><h3>论文（按年份从新到旧）</h3>{papers.map((x,i)=><div className="paper" key={i}><b>{x.year||'年份未知'} · {x.title}</b><div className="muted">{x.source}</div></div>)}</div>:null}<div className="actions"><button onClick={()=>save(p)}><Bookmark size={15}/>加入待开发</button></div></div>}
function Events({data=[]}:{data?:EventItem[]}){if(!data?.length)return null;return <div className="list">{data.map((e,i)=><div className="item" key={i}><div className="itemTop"><div><b style={{fontSize:18}}>{e.name}</b><div>{[e.date,e.city].filter(Boolean).join(' · ')}</div><div className="muted">{e.theme}</div></div><div className="score"><b>{e.value??'-'}</b>/100</div></div>{e.products?.length?<div className="tags">{e.products.map(x=><span className="tag" key={x}>{x}</span>)}</div>:null}{e.why&&<div className="hint">{e.why}</div>}{e.people?.length?<div className="section"><h3>公开嘉宾 / 潜客线索</h3><div className="muted">{e.people.join('、')}</div></div>:null}{e.source&&<div className="muted">来源：{e.source}</div>}</div>)}</div>}
createRoot(document.getElementById('root')!).render(<App/>);