type Msg={role:'system'|'user'|'assistant';content:string};
let chain:Promise<any>=Promise.resolve();let lastStart=0;const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function enqueue<T>(job:()=>Promise<T>){const next=chain.then(job,job);chain=next.catch(()=>{});return next}
function cleanJson(s:string){const t=s.trim().replace(/^```json\s*/i,'').replace(/^```/,'').replace(/```$/,'').trim();const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)return t.slice(a,b+1);return t}
function parse(s:string){try{return JSON.parse(cleanJson(s))}catch{return{error:'AI 返回的数据格式异常，请稍后再试。'}}}
function isRateLimit(x:any){const s=String(x?.message||x||'');return /429|rate_limit|concurrency|max RPM/i.test(s)}
async function moonshot(messages:Msg[]){const key=process.env.MOONSHOT_API_KEY;if(!key)throw new Error('尚未配置 MOONSHOT_API_KEY');const model=process.env.MOONSHOT_MODEL||'kimi-k2.5';const delays=[5000,10000,18000,25000];for(let i=0;i<=delays.length;i++){const gap=21000-(Date.now()-lastStart);if(gap>0)await wait(gap);lastStart=Date.now();try{const r=await fetch('https://api.moonshot.cn/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify({model,messages,temperature:1,response_format:{type:'json_object'},tools:[{type:'builtin_function',function:{name:'$web_search'}}]})});const text=await r.text();if(!r.ok){if((r.status===429||/rate_limit|concurrency|max RPM/i.test(text))&&i<delays.length){await wait(delays[i]);continue}throw new Error(`Moonshot ${r.status}: ${text.slice(0,500)}`)}const j=JSON.parse(text);return j?.choices?.[0]?.message?.content||'{}'}catch(e:any){if(isRateLimit(e)&&i<delays.length){await wait(delays[i]);continue}throw e}}throw new Error('Moonshot 当前较忙，系统自动重试后仍未成功，请稍后再试。')}
const BASE=`你是科研设备销售的客户开拓助手。必须联网搜索，只依据真实公开网页，不得凭记忆编造。只使用公开的工作联系方式；不得猜测私人手机号。论文必须按年份从新到旧。销售判断要把“研究方向适配”与“已经使用设备的证据”分开：食品感官、消费者科学、味觉嗅觉、偏好情绪、自然疗愈、运动认知/疲劳、人因设计、康复、心理认知等即使暂未发现EEG/fNIRS/眼动使用记录，也可能是高价值潜客。产品池包括 EEG、fNIRS近红外脑成像、眼动仪、VR眼动、面部表情、多模态生理/手环、EMG、嗅觉刺激。不要生成微信首次联系、邮件主题、邮件正文、会议前邀约或“下一步”话术。`;
function personShape(extra=''){return `${BASE}\n${extra}\n只输出JSON：{"candidates":[{"name":"","org":"","department":"","title":"","direction":"","score":0,"whyNow":"","products":[],"office":"","campus":"","email":"","phone":"","papers":[{"year":2026,"title":"","source":""}],"projects":[],"equipment":[],"source":""}],"note":""}。score为0-100开拓价值。办公室、电话、邮箱查不到就留空。`}
export default async function handler(req:any,res:any){if(req.method!=='POST')return res.status(405).json({error:'Method Not Allowed'});return enqueue(async()=>{try{const b=req.body||{};let prompt='';if(b.mode==='person')prompt=personShape(`核验并深度调研老师：${b.name}；单位线索：${b.org||'未知'}。优先近3年论文、近期项目、公开办公室/工作联系方式。`);else if(b.mode==='school')prompt=personShape(`扫描学校/学院/实验室：${b.school}。找最多12位最值得科研设备销售陌拜的老师，按score从高到低。尽量核验办公室、校区、工作邮箱、办公电话。另在根JSON增加route字段，按校区/楼栋给出简短陌拜顺序。`);else if(b.mode==='scope')prompt=personShape(`按范围发现潜客：${b.scope}。最多12人，按开拓价值排序。`);else if(b.mode==='opportunities')prompt=personShape(`发现“现在值得联系”的科研客户机会。范围：${b.scope||'中国高校与科研院所，优先认知神经设备适配场景'}。重点找最近论文、新项目/基金、新实验室、近期会议等新鲜信号，最多10人。`);else if(b.mode==='import')prompt=personShape(`用户提供了一批种子名单/同行论文集提取文本：\n${String(b.text||'').slice(0,14000)}\n识别其中真实出现的老师与单位，最多20人；已有设备/方法线索写入equipment，并判断还能切入哪些多模态产品。`);else if(b.mode==='events')prompt=`${BASE}\n今天之后、今年内，搜索与科研设备潜客开发相关的会议/展会。范围：${b.scope||'食品感官、心理认知、体育、康复、管理/消费者研究、设计人因、建筑自然疗愈、教育、化妆品'}。已经结束的活动不要返回。只输出JSON：{"events":[{"name":"","date":"","city":"","theme":"","value":0,"why":"","people":[],"products":[],"source":""}],"note":""}。value为0-100开拓价值；people只列公开嘉宾/报告人/主席等可核验人名。最多12场。`;else return res.status(400).json({error:'未知检索模式'});const raw=await moonshot([{role:'system',content:prompt},{role:'user',content:'请开始联网核验并返回严格JSON。'}]);const out=parse(raw);if(out.error)return res.status(502).json(out);return res.status(200).json(out)}catch(e:any){const s=String(e?.message||e);if(isRateLimit(s))return res.status(503).json({error:'Moonshot 当前有其他检索正在执行，系统已经自动排队和重试；如果仍失败，请稍后再点一次。'});return res.status(500).json({error:s.replace(/Moonshot \d+: /,'').slice(0,500)})}})}